### ISSUE TITLE
Commit Mono not listed as “Fixed Width” in macOS "Font Book.app"

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#15]
In macOS’s Font Book app, if you look in the Fixed Width collection, Commit Mono is not listed. Is the fact that Commit Mono is monospace a missing piece of metadata? (I don't know anything about how font files work or what information they store about themselves, but other monospace fonts I've installed have correctly ended up in the Fixed Width collection.)

**Comment by eigilnikolajsen** [comment]
I will have a look to see if I can fix this, seems pretty crucial.

**Comment by glebd** [comment]
Same on Windows 10.

**Comment by eigilnikolajsen** [comment]
I think I've found the source of the issue. When exporting the font using opentype.js the value 'isFixedPitch' fromt the 'post' table seems to get lost. This value seems to be the indicator of font being monospaced. The default value is 0 and that overrides the 1 that I otherwise put. I've [filed an issue in the opentype.js repository](https://github.com/opentypejs/opentype.js/issues/611), hopefully a new version can fix this problem so the font can be exported with the correct category.

**Comment by eigilnikolajsen** [comment]
Yes, I am sorry about @gaksaray, hoping to fix it as soon as possible. Meanwhile, if you're willing to use the un-customized version, I've created a version for you that should show up in the fixed-width category correctly: [CommitMono-1.134-monospace.zip](https://github.com/eigilnikolajsen/commit-mono/files/12358240/CommitMono-1.134-monospace.zip)

**Comment by gaksaray** [comment]
Thanks @eigilnikolajsen this works! However, I recall your suggestion from the website to use a weight of 500 in light mode environment (which I prefer). If that's the case, I will still be waiting for customized fonts with a fixed width.

**Comment by DwayneBradley-eaton** [comment]
As an additional data point, Windows Terminal doesn't like it either. When choosing the "Font face" in settings, it initially doesn't even show up in the list:

![image](https://github.com/eigilnikolajsen/commit-mono/assets/137190618/6c2b5bc6-7d86-4810-bdb3-cb6dff7ff1a5)

If you choose to "Show all fonts" and then select CommitMono, you get the following warning:

![image](https://github.com/eigilnikolajsen/commit-mono/assets/137190618/e0b430b7-967b-4c73-b8cd-37b52aa25ab7)

**Comment by StreakInTheSky** [comment]
Did some debugging and experimenting and got it to export the correct monospaced font. The released versions of opentype.js doesn't pass in the `post` table when it creates the blob, so it creates a default `post` table. The current `master` has it correctly passed in. I built a script from master and updated `commit-mono`'s download script to use it instead. If anyone wants to use it, can use [my fork](https://github.com/StreakInTheSky/commit-mono/tree/update-openscriptjs).

@eigilnikolajsen Don't know how you feel about using non official release version of a opentype.js, so didn't make a PR, but can make one if you're okay with that.

**Comment by eigilnikolajsen** [comment]
Hey @StreakInTheSky ! Thank you so much for your testing. I'd love if you make a PR, I'm totally fine using a non-official version as long as it works. 

I think this might resolve https://github.com/eigilnikolajsen/commit-mono/issues/62 and https://github.com/eigilnikolajsen/commit-mono/issues/10 as well!

**Comment by eigilnikolajsen** [comment]
Thanks to the help of @StreakInTheSky this should now be resolved in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.140)

**Comment by rossburton** [comment]
I just installed the latest release and it still doesn't appear under Fixed Width in Font Book.

**Comment by eigilnikolajsen** [comment]
Weird. It's difficult to find info on how Font Book recognises fixed-width fonts. My best guess is that it's the panose numbers. I think those are still an issue on OpenType.js.

**Comment by caksoylar** [comment]
FWIW, the newest release can be set as the terminal font on e.g. Windows Terminal without it complaining about not being a fixed width font.

**Comment by stlee42** [comment]
I have found before that some monospaced fonts actually have a few stragglers that are just slightly different width than the rest which prevents it from showing up in that category of macOS's Font Book.app.

I ran the font through the `ttx` tool.

The file you posted ([CommitMono-1.134-monospace.zip](https://github.com/eigilnikolajsen/commit-mono/files/12358240/CommitMono-1.134-monospace.zip)) has in `hhea` table
```
<numberOfHMetrics value="1"/>
```

On the other hand, v1.142 has in `hhea` table
```
<numberOfHMetrics value="1926"/>
```
which seems high to me.

Also, in `CFF` table
```
  <CFF>
    <major value="1"/>
    <minor value="0"/>
    <CFFFont name="CommitMono-Regular">
      <version value="Version 1.134"/>
      <Copyright value="Copyright 2023 Commit Mono authors \(https://github.com/eigilnikolajsen/commit-mono\)"/>
      <FullName value="CommitMono Regular"/>
      <FamilyName value="CommitMono"/>
      <Weight value="News"/>
      <isFixedPitch value="1"/>
```
is how the one you posted in this thread looks like.

And the latest release shows
```
<CFF>
    <major value="1"/>
    <minor value="0"/>
    <CFFFont name="CommitMono-Regular">
      <version value="Version 1.142"/>
      <FullName value="CommitMono Regular"/>
      <FamilyName value="CommitMono"/>
      <Weight value="Regular"/>
      <isFixedPitch value="0"/>
```

Please note the `isFixedPitch`. This is a separate entry that is different than the entry in `post` table.

**Comment by StreakInTheSky** [comment]
So opentype.js has a number of issues with Monospaced font support, the post table was just the most obvious. Did a bunch of research a while back since I had not idea how font files worked before this, but it kind of went on the back burner. Should probably create an issue in over there.

**Comment by shenghui0779** [comment]
I installed the latest release and it still doesn't appear under Fixed Width in Font Book.

**Comment by yvvt0379** [comment]
JetBrains IDEs also doesn't recognise this font as monospaced font. I looked for this font under Proportional category, didn't find it either.
![image](https://github.com/eigilnikolajsen/commit-mono/assets/62426149/9de3bd02-1fe6-48b0-9bd9-c9579ac984ef)
![image](https://github.com/eigilnikolajsen/commit-mono/assets/62426149/ee4d5226-2d70-441a-b839-cccd937a376a)

**Comment by GeographicCone** [comment]
You can try the version with the modifications I described in #75. The changes make it possible to use it with the Windows Console, so maybe they'll work for you too. The files are attached below:

* [CommitMono-1.142-TTF-Mod.zip](https://github.com/eigilnikolajsen/commit-mono/files/14309521/CommitMono-1.142-TTF-Mod.zip)

They're based on _Commit Mono_ version 1.142 of 2023-12-09. The weights are 400 (Regular) and 700 (Bold). Hope it's OK with the author to share it like that, if not please feel free to delete. I can also post the `.ttx` diffs.

**Comment by pean** [comment]
I was really excited to try this font - especially with all the great customisations to my liking - but bumped into this issue. Using MacOS + Kitty and Kitty only recognises fixed widths fonts and it's not listed as that in neither Kitty nor Font Book.

**Comment by nobe4** [comment]
@GeographicCone your version worked for me, thanks for providing this!

**Comment by kirchik95** [comment]
> I was really excited to try this font - especially with all the great customisations to my liking - but bumped into this issue. Using MacOS + Kitty and Kitty only recognises fixed widths fonts and it's not listed as that in neither Kitty nor Font Book.

struggling with same issue :(

**Comment by gaksaray** [comment]
> > I was really excited to try this font - especially with all the great customisations to my liking - but bumped into this issue. Using MacOS + Kitty and Kitty only recognises fixed widths fonts and it's not listed as that in neither Kitty nor Font Book.
> 
> struggling with same issue :(

I can also say that the issue persists on macOS Sequoia 15.3.1 with Commit Mono version 1.143. The font is not identified as "Fixed Width". I hope this gets resolved soon.

**Comment by brzzdev** [comment]
Any update on this, please?

**Comment by JoeGaggler** [comment]
Via https://github.com/eigilnikolajsen/commit-mono/issues/75#issuecomment-1870520623 - I think Eigil is looking for some help from the community for a permanent fix, whether that is a PR for this repo, updates to OpenType.js, or something else.

**Comment by stlee42** [comment]
> Is there an issue I can follow in the OpenType repo? Are they aware of the issue?

Please follow the link in [this comment](https://github.com/eigilnikolajsen/commit-mono/issues/15#issuecomment-1675399058)

**Comment by eigilnikolajsen** [comment]
No updates, unfortunately. If you have news from OpenType.js please bring them forth or submit a PR!

**Comment by stlee42** [comment]
@brzzdev I found more in the trail such as [#69](https://github.com/eigilnikolajsen/commit-mono/issues/69#issuecomment-2345568605) and [#100](https://github.com/eigilnikolajsen/commit-mono/issues/100#issuecomment-2345643811). @Finii has been working generously to provide 3 pull requests to the opentypejs project [1](https://github.com/opentypejs/opentype.js/pull/759) [2](https://github.com/opentypejs/opentype.js/pull/761) [3](https://github.com/opentypejs/opentype.js/pull/762) [all](https://github.com/opentypejs/opentype.js/pulls/Finii)

Since opentypejs project has remained unresponsive, @eigilnikolajsen should follow @Finii's suggestion in the first link of this post.

**Comment by theevocater** [comment]
I wanted to try out CommitMono on OSX this morning and put together a quick script to do the fix suggested by stlee42 via ttx if anyone finds this useful:

```bash
#!/bin/bash

# Install fonttools for ttx
python3 -m venv venv
venv/bin/pip install fonttools

# Convert to ttx
venv/bin/ttx  ./*.otf

# set isFixedPitch to 1
sed -i '' -e 's/isFixedPitch value="0"/isFixedPitch value="1"/g' ./*.ttx

# Convert back to otf
mkdir fixed
venv/bin/ttx -d fixed/ ./*.ttx
```

**Comment by Finii** [comment]
Or just do not use the website and selfwritten opentype.js based download, but download the font directly:

https://github.com/eigilnikolajsen/commit-mono/tree/main/src/fonts/fontlab

It's just the website download process that breaks the font(s) 😒

**Comment by dhisonp** [comment]
> I wanted to try out CommitMono on OSX this morning and put together a quick script to do the fix suggested by stlee42 via ttx if anyone finds this useful:
> ...

Works perfectly fine. Cheers!
